### PR TITLE
Shadcn UI Installation and Setup / Relative path imports

### PR DESCRIPTION
**Pull request by FrederickOB**
This PR introduces the integration of Shadcn into our project, including the installation, setup, and addition of Shadcn components. Additionally, it standardizes the import paths by replacing relative paths with `"@/"`.

### Changes Made

- Installed Shadcn package and its dependencies.
- Set up Shadcn in the project configuration.
- Added Shadcn components to enhance functionality.
- Refactored import paths, replacing relative paths with `"@/"` for better organization and consistency.

### CODE REVIEW

**Comment by tsikatawill** [comment]
There are some merge conflicts in `Login.tsx`. Please look into it

**Comment by tsikatawill** [comment]
There are some merge conflicts in `Login.tsx`. Please look into it

**Comment by tsikatawill** [comment]
We had some colors setup in `tailwind.config`. They have been over-written by Shadcn. Please bring back our initial configs.
image

**Comment by tsikatawill** [comment]
We had some colors setup in `tailwind.config`. They have been over-written by Shadcn. Please bring back our initial configs.
image

**Comment by FrederickOB** [comment]
> We had some colors setup in `tailwind.config`. They have been over-written by Shadcn. Please bring back our initial configs. image

brought them back

**Comment by FrederickOB** [comment]
> There are some merge conflicts in `Login.tsx`. Please look into it

Fixed merge conflict

**Pull request merged**
